name: Update Meteo CSV

on:
  schedule:
    - cron: "5 9 * * *"   # 09:05 UTC = 06:05 America/Argentina/Buenos_Aires
  workflow_dispatch: {}     # botón "Run workflow" en GitHub

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy pytz

      - name: Update CSV from API
        env:
          METEOBAHIA_URL: https://meteobahia.com.ar/scripts/forecast/for-bb.xml  # <--- AJUSTAR localidad
          PRON_DIAS_API: 8
        run: |
          python update_meteo.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/meteo_daily.csv
          git diff --staged --quiet || git commit -m "Auto-update meteo_daily.csv"
          git push

